### ISSUE TITLE
PreTeX CSS styling does not correctly generate in Web Preview under pretext==2.0.1

### ISSUE THREAD

**Issue by smithea3** [PreTeXtBook/pretext-codespace#18]
When generating the web files for a "book" using pretext version 2.0.1, the web version does not seem to correctly generate or link to the CSS files as specified in the documentation. However, when I downgrade the codespace to v 1.8.0 and update the project.ptx file to the original targets method, this resolves the issue.

Perhaps this is me being rather new to to using PreTeX and codespaces, but I wanted to put this here in the event this is in fact an issue with the code.

**Comment by smithea3** [comment]
Sure! Here is a repository that I created from the pretext-codespaces template: [https://github.com/smithea3/calculus-worksheets](https://github.com/smithea3/calculus-worksheets). It is a completely new repository with the GitHub-pages deployment. The formatting of the "Exercises" in the html-generated code does not behave as it should with the styling and formatting. Here is a link to the gh-pages with the exercises/solution: [https://smithea3.github.io/calculus-worksheets/sec-section-name.html](https://smithea3.github.io/calculus-worksheets/sec-section-name.html).

**Comment by oscarlevin** [comment]
Ah!  You mean that it doesn't have the pink background any more?  That is actually because core pretext has updated the way that these hidden element show up.  So I don't think anything here is broken, but if you would like to request different styling of these elements, please make a post on the pretext-support forum: https://groups.google.com/g/pretext-support.
